import { ImageMetadata } from '../types/museum';

export const drawingImages: ImageMetadata[] = [
  {
    id: 'static-lux-perpetua',
    url: '/art/placeholder-horizon.svg',
    aspectRatio: 800 / 1000,
    title: 'Lux Perpetua',
    artist: 'Mira Solenne',
    date: '2024',
    medium: 'Digital illustration',
    link: '#',
    shortDescription: 'A quiet study of soft light, muted edges, and a calm horizon.',
    longDescription:
      `This piece uses a narrow range of pale color to create a steady, quiet atmosphere. The central glow is intentionally soft rather than dramatic, giving the image a slow and open feeling.\n\nThe surrounding marks add texture without pulling attention away from the light. For audio testing, the description gives the voice a mix of short and medium-length sentences with a calm visual focus.`,
  },
  {
    id: 'static-hora-incerta',
    url: '/art/placeholder-ember.svg',
    aspectRatio: 900 / 660,
    title: 'Hora Incerta',
    artist: 'Jonas Vale',
    date: '2024',
    medium: 'Watercolour on paper',
    link: '#',
    shortDescription: 'A warm abstract composition about uncertain time and gentle repetition.',
    contentNotes: ['sensory-intensity'],
    longDescription:
      `The title means uncertain hour. The image is built from warm areas of color that seem to shift in and out of focus, suggesting time as something soft rather than sharply measured.\n\nThe darker passages give the composition weight, while the lighter marks create a sense of movement across the surface. For audio testing, this description includes longer sentences and gentle transitions so the narration can be evaluated for pacing and clarity.`,
  },
  {
    id: 'static-silva-quieta',
    url: '/art/placeholder-thicket.svg',
    aspectRatio: 700 / 910,
    title: 'Silva Quieta',
    artist: 'Elena Marlow',
    date: '2024',
    medium: 'Pencil on paper',
    link: '#',
    shortDescription: 'A detailed pencil study of dense forms, quiet rhythm, and layered marks.',
    longDescription:
      `Silva Quieta means quiet wood. The drawing is made from repeated pencil marks that build up into a dense but restrained image. The overall effect is still and textured, with small variations becoming more visible over time.\n\nThe composition is useful for narration testing because it gives the voice concrete visual details to describe without needing a strongly personal story.`,
  },
  {
    id: 'static-aqua-lenis',
    url: '/art/placeholder-tide.svg',
    aspectRatio: 910 / 700,
    title: 'Aqua Lenis',
    artist: 'Noor Avel',
    date: '2024',
    medium: 'Oil pastel',
    link: '#',
    shortDescription: 'A soft pastel image of water, rounded movement, and muted color.',
    longDescription:
      `This work imagines water as a slow visual rhythm. The surface is calm, but the rounded shapes suggest a gentle movement beneath it. The colors are muted so the image can feel open and easy to look at.\n\nThe description gives the audio voice simple sensory language: surface, color, rhythm, and return. It is meant as practical test copy rather than a personal statement.`,
  },
  {
    id: 'static-noctis-figura',
    url: '/art/placeholder-night.svg',
    aspectRatio: 730 / 920,
    title: 'Noctis Figura',
    artist: 'Theo Ibarra',
    date: '2024',
    medium: 'Ink on card',
    link: '#',
    shortDescription: 'A dark ink composition with a quiet figure emerging from the background.',
    contentNotes: ['dark-imagery'],
    longDescription:
      `Noctis Figura uses a dark field with small tonal shifts so the surface does not feel flat. A partial figure appears from the background, giving the image a quiet focal point without making it too literal.\n\nThe work is useful for audio testing because it asks the narration to describe low contrast, atmosphere, and subtle visual detail in a clear and unhurried way.`,
  },
  {
    id: 'static-sine-titulo',
    url: '/art/placeholder-abstract.svg',
    aspectRatio: 800 / 800,
    title: 'Sine Titulo',
    artist: 'Lena Orsini',
    date: '2023',
    medium: 'Digital',
    link: '#',
    shortDescription: 'An untitled abstract image made from simple color blocks and loose structure.',
    longDescription:
      `This untitled piece keeps the composition deliberately open. Blocks of color and loose shapes sit beside each other without resolving into a single subject, leaving room for different readings.\n\nThe copy is intentionally simple for testing. It gives the audio model a short description, a longer description, and a few visual terms without adding a specific personal narrative.`,
  },
  { url: '', title: '', artist: '', date: '', link: '', aspectRatio: 1, isEmpty: true },
  { url: '', title: '', artist: '', date: '', link: '', aspectRatio: 1, isEmpty: true },
];
